version: '3.3'

services:
    nextjsdocker:
        image: nextjsdocker
        networks:
            - web
        deploy: # Deploy via docker stack
            mode: replicated
            replicas: 1
            restart_policy:
                condition: on-failure
            labels:
                - "traefik.enable=true"
                - "traefik.docker.network=web, websecure"
                - "traefik.http.routers.nextjsdocker.entrypoints=web,websecure"
                - "traefik.http.routers.nextjsdocker.rule=Host(`my.host.com`)"
                - "traefik.http.services.nextjsdocker.tls=true"
                - "traefik.http.routers.nextjsdocker.tls.certresolver=production"