version: "3.5"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nextjs
    volumes:
      - .:/app
      - /app/node_modules
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.nextjs.entrypoints=web,websecure"
      - "traefik.http.routers.nextjs.rule=Host(`next.mydao.fr`)"
      - "traefik.http.routers.nextjs.tls=true"
      - "traefik.http.routers.nextjs.tls.certresolver=production"
