version: "3.5"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nextjs
    volumes:
      - .:/app
      -  /app/node_modules
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.dockernext.entrypoints=web, websecure"
      - "traefik.http.routers.dockernext.rule=Host(`next.mydao.fr`)"
      - "traefik.http.routers.dockernext.tls=true"
      - "traefik.http.routers.dockernext.tls.certresolver=prodution"